AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Demo API
Parameters:
  USERPOOLID : {Type: String, Default: 'eu-west-5_6yvacmm58'}
  CLIENTID : {Type: String, Default: '3uc8ocebm3ivir65ul6cnvvril'}
  STAGE    : {Type: String, Default: 'Dev'}
Resources:
  BGGetDonations:
    Type: AWS::Serverless::Function
    Properties:
      Handler: demo.handler
      Runtime: nodejs12.x
      MemorySize: 512
      FunctionName: demo
      Timeout: 7
      Role: arn:aws:iam::957010591412:role/basic-lambda-function
      CodeUri: ./
      Environment:
        Variables: 
          UserPoolId : {Ref : USERPOOLID}
          ClientId   : {Ref : CLIENTID}
          Stage      : {Ref : STAGE}